"""
A py script to run More Practice script functions 
"""
# importing the script 
import MorePractice

# declaring a variable sentence 
sentence = "All good things come to those who wait"

# breaking sentrence to words 
words = MorePractice.break_words(sentence)

# printing the word 
print("The Words in {} are : \n {}".format(sentence,words))

# sorting the words 
sorted_words = MorePractice.sort_words(words)
print("The words in {} sorted are : \n{}".format(sentence,sorted_words))

# printing first word of sorted words 
print(MorePractice.print_first_word(sorted_words))

# printing the last words of sorted words 
print(MorePractice.print_last_word(sorted_words))

# new list of words in sorted order 
print("New List of words : \n{}".format(sorted_words))

# sorting a sentence directly using sort sentence 
sorted_words = MorePractice.sort_sentence(sentence)

# printing the sorted words generated by above sentence
print("The words in {} sorted sequence : \n{}".format(sentence,sorted_words))

# printing first and last words of sentence
print(MorePractice.print_first_and_last(sentence))

# printing first and last words of sentence in sorted sequence 
print(MorePractice.print_first_and_last_sorted(sentence))